{
    "name": "Grupos de Pago con Múltiples Métodos",
    "version": "19.0.1.0.0",
    "category": "Accounting",
    "icon": '/account/static/description/icon.png',
    "author": "ADHOC SA, Exemax, Codize, Birtum",
    "license": "AGPL-3",
    "application": False,
    'installable': True,
    "depends": [
        "account",
        "accountant",
        "mail",
    ],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizards/account_payment_group_invoice_wizard_view.xml',
        'wizards/res_config_settings_views.xml',
        'views/account_payment_view.xml',
        'views/account_move_line_view.xml',
        'views/account_move_view.xml',
        'views/account_payment_group_view.xml',
        'views/account_payment_receiptbook_view.xml',
        #'views/account_journal_dashboard_view.xml',
        'report/report_payment_group.xml',
        #'data/mail_template_data.xml',
    ],
    #"post_init_hook": "post_init_hook",
    "demo": [],
}
